//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Cico.Models;

namespace Cico
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public Case()
        {
            this.Documents = new HashSet<Document>();
            this.CheckLists = new HashSet<CheckList>();
        }
    
        public int Id { get; set; }
        public string DueDate { get; set; }
        public string Type { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<CheckList> CheckLists { get; set; }
    }
}
