//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckList
    {
        public CheckList()
        {
            this.Departments = new HashSet<Department>();
            this.Items = new HashSet<Item>();
            this.Documents = new HashSet<Document>();
        }
    
        public int Id { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public int CaseId { get; set; }
        public int EmployeeEmployeeId { get; set; }
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string DueDate { get; set; }
    
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual Case Case { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
    }
}
