//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cico.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class CheckList_Mapping : EntityTypeConfiguration<CheckList>
    {
        public CheckList_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("CheckLists");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Type).HasColumnName("Type");
              this.Property(t => t.Name).HasColumnName("Name").IsRequired();
              this.Property(t => t.EmployeeEmployeeId).HasColumnName("EmployeeEmployeeId");
              this.Property(t => t.StartDate).HasColumnName("StartDate").IsRequired();
              this.Property(t => t.EndDate).HasColumnName("EndDate").IsRequired();
              this.Property(t => t.DueDate).HasColumnName("DueDate").IsRequired();
              this.HasRequired(t => t.Employee).WithMany(t => t.CheckLists).HasForeignKey(d => d.EmployeeEmployeeId);
         }
    }
}
