//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cico.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class CheckListItem_Mapping : EntityTypeConfiguration<CheckListItem>
    {
        public CheckListItem_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("CheckListItems");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Type).HasColumnName("Type").IsRequired();
              this.Property(t => t.Name).HasColumnName("Name").IsRequired();
              this.Property(t => t.Description).HasColumnName("Description").IsRequired();
              this.Property(t => t.Department).HasColumnName("Department").IsRequired();
              this.Property(t => t.Priority).HasColumnName("Priority").IsRequired();
              this.Property(t => t.Status).HasColumnName("Status").IsRequired();
              this.Property(t => t.Viewable).HasColumnName("Viewable").IsRequired();
              this.Property(t => t.Subscriber).HasColumnName("Subscriber").IsRequired();
              this.Property(t => t.CheckListId).HasColumnName("CheckListId");
              this.Property(t => t.DueDate).HasColumnName("DueDate").IsRequired();
              this.Property(t => t.DueDate1).HasColumnName("DueDate1");
              this.Property(t => t.InstructionDocument).HasColumnName("InstructionDocument").IsRequired();
              this.Property(t => t.EmployeeCompleted).HasColumnName("EmployeeCompleted").IsRequired();
              this.Property(t => t.Provisional).HasColumnName("Provisional").IsRequired();
              this.Property(t => t.OfficeComplete).HasColumnName("OfficeComplete").IsRequired();
              this.Property(t => t.ItemDocument).HasColumnName("ItemDocument").IsRequired();
              this.Property(t => t.BlankForm).HasColumnName("BlankForm").IsRequired();
              this.Property(t => t.InstructionText).HasColumnName("InstructionText").IsRequired();
              this.Property(t => t.Group).HasColumnName("Group").IsRequired();
              this.Property(t => t.AlertDays).HasColumnName("AlertDays").IsRequired();
              this.Property(t => t.AlertFrequency).HasColumnName("AlertFrequency").IsRequired();
              this.HasRequired(t => t.CheckList).WithMany(t => t.CheckListItems).HasForeignKey(d => d.CheckListId);
         }
    }
}
