//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cico.Models
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Document_Mapping : EntityTypeConfiguration<Document>
    {
        public Document_Mapping()
        {                        
              this.HasKey(t => t.DocumentId);        
              this.ToTable("Documents");
              this.Property(t => t.DocumentId).HasColumnName("DocumentId");
              this.Property(t => t.FileName).HasColumnName("FileName").HasMaxLength(255);
              this.Property(t => t.DocId).HasColumnName("DocId").HasMaxLength(255);
              this.Property(t => t.ContentType).HasColumnName("ContentType").HasMaxLength(255);
              this.Property(t => t.CheckListId).HasColumnName("CheckListId");
              this.HasRequired(t => t.CheckList).WithMany(t => t.Documents).HasForeignKey(d => d.CheckListId);
         }
    }
}
