//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses_ExpenseVouchers
    {
        public Expenses_ExpenseVouchers()
        {
            this.Expenses_Expenses = new HashSet<Expenses_Expenses>();
            this.Expenses_ExpenseVoucherCases = new HashSet<Expenses_ExpenseVoucherCases>();
            this.Expenses_Reviews = new HashSet<Expenses_Reviews>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Status { get; set; }
        public string Expensevoucherscol1 { get; set; }
        public Nullable<int> UserFk { get; set; }
    
        public virtual ICollection<Expenses_Expenses> Expenses_Expenses { get; set; }
        public virtual ICollection<Expenses_ExpenseVoucherCases> Expenses_ExpenseVoucherCases { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
        public virtual ICollection<Expenses_Reviews> Expenses_Reviews { get; set; }
    }
}
