//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses_Companies
    {
        public Expenses_Companies()
        {
            this.HighPoint_Users = new HashSet<HighPoint_Users>();
            this.Expenses_Projects = new HashSet<Expenses_Projects>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        public virtual ICollection<HighPoint_Users> HighPoint_Users { get; set; }
        public virtual ICollection<Expenses_Projects> Expenses_Projects { get; set; }
    }
}
