//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses_Projects
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> PerDiem { get; set; }
        public Nullable<int> CompanyFk { get; set; }
    
        public virtual Expenses_Companies Expenses_Companies { get; set; }
    }
}
