//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_ProcessForms
    {
        public HighPoint_ProcessForms()
        {
            this.HighPoint_BusinessProcesses1 = new HashSet<HighPoint_BusinessProcesses>();
            this.HighPoint_ProcessFormBookmarks = new HashSet<HighPoint_ProcessFormBookmarks>();
            this.HighPoint_StateCompletionTracks = new HashSet<HighPoint_StateCompletionTracks>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> BusinessProcessFk { get; set; }
        public Nullable<int> ProcessingCaseFk { get; set; }
    
        public virtual HighPoint_BusinessProcesses HighPoint_BusinessProcesses { get; set; }
        public virtual ICollection<HighPoint_BusinessProcesses> HighPoint_BusinessProcesses1 { get; set; }
        public virtual HighPoint_NavigatorProcessForms HighPoint_NavigatorProcessForms { get; set; }
        public virtual HighPoint_ProcessAutoForms HighPoint_ProcessAutoForms { get; set; }
        public virtual ICollection<HighPoint_ProcessFormBookmarks> HighPoint_ProcessFormBookmarks { get; set; }
        public virtual HighPoint_ProcessingCases HighPoint_ProcessingCases { get; set; }
        public virtual ICollection<HighPoint_StateCompletionTracks> HighPoint_StateCompletionTracks { get; set; }
    }
}
