//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_Reports
    {
        public HighPoint_Reports()
        {
            this.HighPoint_Roles = new HashSet<HighPoint_Roles>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string DataProviderName { get; set; }
        public Nullable<int> ReportType { get; set; }
        public Nullable<bool> CrystalGroup { get; set; }
        public Nullable<bool> CrystalToolbar { get; set; }
        public int ReportCategoryFk { get; set; }
    
        public virtual HighPoint_ReportCategories HighPoint_ReportCategories { get; set; }
        public virtual ICollection<HighPoint_Roles> HighPoint_Roles { get; set; }
    }
}
