//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_Addresses
    {
        public HighPoint_Addresses()
        {
            this.MFH_Units = new HashSet<MFH_Units>();
            this.HighPoint_People = new HashSet<HighPoint_People>();
        }
    
        public int Id { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    
        public virtual ICollection<MFH_Units> MFH_Units { get; set; }
        public virtual ICollection<HighPoint_People> HighPoint_People { get; set; }
    }
}
