//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_UserGroups
    {
        public HighPoint_UserGroups()
        {
            this.HighPoint_ProcessingEntities = new HashSet<HighPoint_ProcessingEntities>();
            this.HighPoint_Users = new HashSet<HighPoint_Users>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int SupervisorFk { get; set; }
    
        public virtual ICollection<HighPoint_ProcessingEntities> HighPoint_ProcessingEntities { get; set; }
        public virtual ICollection<HighPoint_Users> HighPoint_Users { get; set; }
        public virtual HighPoint_Users HighPoint_Users1 { get; set; }
    }
}
