//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_StateItemAudits
    {
        public int Id { get; set; }
        public Nullable<int> Action { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<int> CaseBusinessActivityLogFk { get; set; }
        public Nullable<int> UserFk { get; set; }
        public Nullable<int> StateItemFk { get; set; }
    
        public virtual HighPoint_CaseBusinessActivityLogs HighPoint_CaseBusinessActivityLogs { get; set; }
        public virtual HighPoint_StateItems HighPoint_StateItems { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
    }
}
