//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_AutoFormItems
    {
        public HighPoint_AutoFormItems()
        {
            this.HighPoint_AutoFormItemInstances = new HashSet<HighPoint_AutoFormItemInstances>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InputType { get; set; }
        public Nullable<int> DataType { get; set; }
        public string Label { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Required { get; set; }
        public string Options { get; set; }
        public int AutoFormFk { get; set; }
    
        public virtual ICollection<HighPoint_AutoFormItemInstances> HighPoint_AutoFormItemInstances { get; set; }
        public virtual HighPoint_AutoForms HighPoint_AutoForms { get; set; }
    }
}
