//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_StateCompletionTracks
    {
        public HighPoint_StateCompletionTracks()
        {
            this.HighPoint_ProcessingCases = new HashSet<HighPoint_ProcessingCases>();
            this.HighPoint_StateItems = new HashSet<HighPoint_StateItems>();
            this.HighPoint_StateCompletionTracks1 = new HashSet<HighPoint_StateCompletionTracks>();
        }
    
        public int Id { get; set; }
        public string WorkflowName { get; set; }
        public string StateDescription { get; set; }
        public string BookmarkName { get; set; }
        public Nullable<int> PromptName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<bool> Completed { get; set; }
        public string WorkflowInstanceId { get; set; }
        public string UserData { get; set; }
        public Nullable<int> HelpPage { get; set; }
        public Nullable<int> PreviousStateFk { get; set; }
        public Nullable<int> ProcessFormFk { get; set; }
        public Nullable<int> UserCompletedFk { get; set; }
        public int ProcessingCaseFk { get; set; }
    
        public virtual HighPoint_ProcessForms HighPoint_ProcessForms { get; set; }
        public virtual ICollection<HighPoint_ProcessingCases> HighPoint_ProcessingCases { get; set; }
        public virtual HighPoint_ProcessingCases HighPoint_ProcessingCases1 { get; set; }
        public virtual ICollection<HighPoint_StateItems> HighPoint_StateItems { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
        public virtual ICollection<HighPoint_StateCompletionTracks> HighPoint_StateCompletionTracks1 { get; set; }
        public virtual HighPoint_StateCompletionTracks HighPoint_StateCompletionTracks2 { get; set; }
    }
}
