//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_StateItems
    {
        public HighPoint_StateItems()
        {
            this.HighPoint_StateItemAudits = new HashSet<HighPoint_StateItemAudits>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Description { get; set; }
        public Nullable<int> UserCreatedFk { get; set; }
        public int StateCompletionTrackFk { get; set; }
    
        public virtual HighPoint_CaseNotes HighPoint_CaseNotes { get; set; }
        public virtual HighPoint_FormTracks HighPoint_FormTracks { get; set; }
        public virtual HighPoint_StateCompletionTracks HighPoint_StateCompletionTracks { get; set; }
        public virtual HighPoint_StateDocuments HighPoint_StateDocuments { get; set; }
        public virtual ICollection<HighPoint_StateItemAudits> HighPoint_StateItemAudits { get; set; }
        public virtual HighPoint_TaskBases HighPoint_TaskBases { get; set; }
        public virtual HighPoint_TrackTimeItems HighPoint_TrackTimeItems { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
        public virtual HighPoint_WorkflowTracks HighPoint_WorkflowTracks { get; set; }
    }
}
