//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_StateDocuments
    {
        public int StateItemFk { get; set; }
        public Nullable<int> DocumentFk { get; set; }
    
        public virtual HighPoint_CaseDocuments HighPoint_CaseDocuments { get; set; }
        public virtual HighPoint_StateItems HighPoint_StateItems { get; set; }
    }
}
