//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_Forms
    {
        public HighPoint_Forms()
        {
            this.HighPoint_FormTracks = new HashSet<HighPoint_FormTracks>();
            this.HighPoint_BusinessProcesses = new HashSet<HighPoint_BusinessProcesses>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileDocumentFk { get; set; }
        public Nullable<int> CreatorFk { get; set; }
        public int DocumentTypeFk { get; set; }
    
        public virtual HighPoint_Documents HighPoint_Documents { get; set; }
        public virtual HighPoint_DocumentTypes HighPoint_DocumentTypes { get; set; }
        public virtual ICollection<HighPoint_FormTracks> HighPoint_FormTracks { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
        public virtual ICollection<HighPoint_BusinessProcesses> HighPoint_BusinessProcesses { get; set; }
    }
}
