//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_Reminders
    {
        public int TaskBaseFk { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual HighPoint_TaskBases HighPoint_TaskBases { get; set; }
    }
}
