//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_Suggestions
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime EnterDate { get; set; }
        public string Status { get; set; }
        public int CreatorFk { get; set; }
    
        public virtual HighPoint_Users HighPoint_Users { get; set; }
    }
}
