//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_TaskBases
    {
        public int StateItemFk { get; set; }
        public Nullable<System.DateTime> CompletedTime { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> UserCompletedFk { get; set; }
    
        public virtual HighPoint_Reminders HighPoint_Reminders { get; set; }
        public virtual HighPoint_StateItems HighPoint_StateItems { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
        public virtual HighPoint_Tasks HighPoint_Tasks { get; set; }
    }
}
