//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_ProcessingEntities
    {
        public HighPoint_ProcessingEntities()
        {
            this.HighPoint_CaseDocuments = new HashSet<HighPoint_CaseDocuments>();
            this.HighPoint_ProcessingCases = new HashSet<HighPoint_ProcessingCases>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> GroupFk { get; set; }
    
        public virtual Expenses_VoucherEmployees Expenses_VoucherEmployees { get; set; }
        public virtual ICollection<HighPoint_CaseDocuments> HighPoint_CaseDocuments { get; set; }
        public virtual ICollection<HighPoint_ProcessingCases> HighPoint_ProcessingCases { get; set; }
        public virtual HighPoint_UserGroups HighPoint_UserGroups { get; set; }
        public virtual MFH_Households MFH_Households { get; set; }
        public virtual MFH_MfhContracts MFH_MfhContracts { get; set; }
        public virtual Slv_Students Slv_Students { get; set; }
    }
}
