//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_WorkflowStatuses
    {
        public HighPoint_WorkflowStatuses()
        {
            this.HighPoint_ProcessingCases = new HashSet<HighPoint_ProcessingCases>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<HighPoint_ProcessingCases> HighPoint_ProcessingCases { get; set; }
    }
}
