//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseholdPeople
    {
        public HouseholdPeople()
        {
            this.Households = new HashSet<Household>();
            this.WorksheetItems = new HashSet<WorksheetItem>();
        }
    
        public int HouseholdPersonId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RelationToHead { get; set; }
        public Nullable<System.DateTime> Dob { get; set; }
        public string Mi { get; set; }
        public Nullable<bool> Disability { get; set; }
        public string Race { get; set; }
        public string Ethnicity { get; set; }
        public string Ssn { get; set; }
        public Nullable<int> HouseholdId { get; set; }
    
        public virtual ICollection<Household> Households { get; set; }
        public virtual Household Household { get; set; }
        public virtual ICollection<WorksheetItem> WorksheetItems { get; set; }
    }
}
