//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeWorksheet
    {
        public IncomeWorksheet()
        {
            this.WorksheetItems = new HashSet<WorksheetItem>();
        }
    
        public int IncomeWorksheetId { get; set; }
        public Nullable<int> HouseholdCaseId { get; set; }
    
        public virtual HouseholdCase HouseholdCase { get; set; }
        public virtual ICollection<WorksheetItem> WorksheetItems { get; set; }
    }
}
