//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letter
    {
        public int LetterId { get; set; }
        public Nullable<int> LetterDefinitionId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> DocumentId { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual LetterDefinition LetterDefinition { get; set; }
        public virtual Task Task { get; set; }
    }
}
