//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFH_HouseholdPeople
    {
        public MFH_HouseholdPeople()
        {
            this.MFH_EconomyElements = new HashSet<MFH_EconomyElements>();
            this.MFH_Households = new HashSet<MFH_Households>();
        }
    
        public int PersonFk { get; set; }
        public Nullable<int> HouseholdRole { get; set; }
        public Nullable<int> HouseholdFk { get; set; }
    
        public virtual HighPoint_People HighPoint_People { get; set; }
        public virtual ICollection<MFH_EconomyElements> MFH_EconomyElements { get; set; }
        public virtual ICollection<MFH_Households> MFH_Households { get; set; }
        public virtual MFH_Households MFH_Households1 { get; set; }
    }
}
