//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFH_MfhContracts
    {
        public int ProcessingEntityFk { get; set; }
        public string ContractNo { get; set; }
        public string PropertyName { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> RenewalDate { get; set; }
    
        public virtual HighPoint_ProcessingEntities HighPoint_ProcessingEntities { get; set; }
    }
}
