//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFH_RecertificationCases
    {
        public int HouseholdCaseFk { get; set; }
        public Nullable<System.DateTime> DueMonth { get; set; }
        public Nullable<System.DateTime> FirstInterviewDate { get; set; }
        public Nullable<System.DateTime> SecondInterviewDate { get; set; }
        public Nullable<int> RecertificationResult { get; set; }
    
        public virtual MFH_HouseholdCases MFH_HouseholdCases { get; set; }
    }
}
