//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFH_Households
    {
        public MFH_Households()
        {
            this.MFH_HouseholdCases = new HashSet<MFH_HouseholdCases>();
            this.MFH_HouseholdPeople1 = new HashSet<MFH_HouseholdPeople>();
        }
    
        public int ProcessingEntityFk { get; set; }
        public string TenantId { get; set; }
        public Nullable<System.DateTime> NextRecertificationDate { get; set; }
        public Nullable<System.DateTime> OriginalMoveInDate { get; set; }
        public Nullable<int> UnitFk { get; set; }
        public Nullable<int> TenantFk { get; set; }
    
        public virtual HighPoint_ProcessingEntities HighPoint_ProcessingEntities { get; set; }
        public virtual ICollection<MFH_HouseholdCases> MFH_HouseholdCases { get; set; }
        public virtual MFH_HouseholdPeople MFH_HouseholdPeople { get; set; }
        public virtual ICollection<MFH_HouseholdPeople> MFH_HouseholdPeople1 { get; set; }
        public virtual MFH_Units MFH_Units { get; set; }
    }
}
