//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessType
    {
        public ProcessType()
        {
            this.TaskDefinitions = new HashSet<TaskDefinition>();
            this.SystemCases = new HashSet<SystemCas>();
        }
    
        public int ProcessTypeId { get; set; }
        public string Description { get; set; }
        public string CreationUrl { get; set; }
    
        public virtual ICollection<TaskDefinition> TaskDefinitions { get; set; }
        public virtual ICollection<SystemCas> SystemCases { get; set; }
    }
}
