//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slv_Students
    {
        public Slv_Students()
        {
            this.Slv_LoanVerificationCases = new HashSet<Slv_LoanVerificationCases>();
        }
    
        public int ProcessingEntityFk { get; set; }
        public string Description { get; set; }
        public int PersonFk { get; set; }
    
        public virtual HighPoint_People HighPoint_People { get; set; }
        public virtual HighPoint_ProcessingEntities HighPoint_ProcessingEntities { get; set; }
        public virtual ICollection<Slv_LoanVerificationCases> Slv_LoanVerificationCases { get; set; }
    }
}
