//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorksheetItem
    {
        public int WorksheetItemId { get; set; }
        public string ItemType { get; set; }
        public string IncomeCode { get; set; }
        public Nullable<int> IncomeWorksheetId { get; set; }
        public Nullable<int> HouseholdPersonId { get; set; }
        public Nullable<int> EmployerId { get; set; }
    
        public virtual Employer Employer { get; set; }
        public virtual HouseholdPeople HouseholdPeople { get; set; }
        public virtual IncomeWorksheet IncomeWorksheet { get; set; }
    }
}
