//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses_Reviews
    {
        public int Id { get; set; }
        public Nullable<int> Role { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ExpenseVoucherFk { get; set; }
    
        public virtual Expenses_ExpenseVouchers Expenses_ExpenseVouchers { get; set; }
    }
}
