//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_ProcessingCases
    {
        public HighPoint_ProcessingCases()
        {
            this.HighPoint_AutoFormInstances = new HashSet<HighPoint_AutoFormInstances>();
            this.HighPoint_CaseBusinessActivityLogs = new HashSet<HighPoint_CaseBusinessActivityLogs>();
            this.HighPoint_CaseDocuments = new HashSet<HighPoint_CaseDocuments>();
            this.HighPoint_CaseNotes = new HashSet<HighPoint_CaseNotes>();
            this.HighPoint_ProcessForms = new HashSet<HighPoint_ProcessForms>();
            this.HighPoint_WorkflowBookmarks = new HashSet<HighPoint_WorkflowBookmarks>();
            this.HighPoint_StateCompletionTracks1 = new HashSet<HighPoint_StateCompletionTracks>();
            this.HighPoint_WorkflowTracks = new HashSet<HighPoint_WorkflowTracks>();
            this.HighPoint_CaseDocuments1 = new HashSet<HighPoint_CaseDocuments>();
        }
    
        public int Id { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<bool> NewDocument { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> CasePriority { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> RootWorkflowId { get; set; }
        public Nullable<int> CurrentCompletionStateFk { get; set; }
        public Nullable<int> BusinessProcessFk { get; set; }
        public Nullable<int> WorkflowStatusFk { get; set; }
        public Nullable<int> ProcessingEntityFk { get; set; }
        public Nullable<int> CreatorFk { get; set; }
        public Nullable<int> OwnerFk { get; set; }
    
        public virtual Expenses_ExpenseVoucherCases Expenses_ExpenseVoucherCases { get; set; }
        public virtual ICollection<HighPoint_AutoFormInstances> HighPoint_AutoFormInstances { get; set; }
        public virtual HighPoint_BusinessProcesses HighPoint_BusinessProcesses { get; set; }
        public virtual ICollection<HighPoint_CaseBusinessActivityLogs> HighPoint_CaseBusinessActivityLogs { get; set; }
        public virtual ICollection<HighPoint_CaseDocuments> HighPoint_CaseDocuments { get; set; }
        public virtual ICollection<HighPoint_CaseNotes> HighPoint_CaseNotes { get; set; }
        public virtual ICollection<HighPoint_ProcessForms> HighPoint_ProcessForms { get; set; }
        public virtual MFH_HouseholdCases MFH_HouseholdCases { get; set; }
        public virtual ICollection<HighPoint_WorkflowBookmarks> HighPoint_WorkflowBookmarks { get; set; }
        public virtual MFH_PropertyCases MFH_PropertyCases { get; set; }
        public virtual HighPoint_ProcessingEntities HighPoint_ProcessingEntities { get; set; }
        public virtual HighPoint_StateCompletionTracks HighPoint_StateCompletionTracks { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
        public virtual HighPoint_WorkflowStatuses HighPoint_WorkflowStatuses { get; set; }
        public virtual HighPoint_Users HighPoint_Users1 { get; set; }
        public virtual ICollection<HighPoint_StateCompletionTracks> HighPoint_StateCompletionTracks1 { get; set; }
        public virtual Slv_LoanVerificationCases Slv_LoanVerificationCases { get; set; }
        public virtual ICollection<HighPoint_WorkflowTracks> HighPoint_WorkflowTracks { get; set; }
        public virtual ICollection<HighPoint_CaseDocuments> HighPoint_CaseDocuments1 { get; set; }
    }
}
