//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_CaseNotes
    {
        public int StateItemFk { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Content { get; set; }
        public Nullable<int> UserUpdatedFk { get; set; }
        public Nullable<int> ProcessingCaseFk { get; set; }
    
        public virtual HighPoint_StateItems HighPoint_StateItems { get; set; }
        public virtual HighPoint_ProcessingCases HighPoint_ProcessingCases { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
    }
}
