//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_AutoForms
    {
        public HighPoint_AutoForms()
        {
            this.HighPoint_AutoFormInstances = new HashSet<HighPoint_AutoFormInstances>();
            this.HighPoint_AutoFormItems = new HashSet<HighPoint_AutoFormItems>();
            this.HighPoint_ProcessAutoForms = new HashSet<HighPoint_ProcessAutoForms>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Desctiption { get; set; }
    
        public virtual ICollection<HighPoint_AutoFormInstances> HighPoint_AutoFormInstances { get; set; }
        public virtual ICollection<HighPoint_AutoFormItems> HighPoint_AutoFormItems { get; set; }
        public virtual ICollection<HighPoint_ProcessAutoForms> HighPoint_ProcessAutoForms { get; set; }
    }
}
