//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_DocumentTypes
    {
        public HighPoint_DocumentTypes()
        {
            this.HighPoint_DocTypeWorkflowBookmarks = new HashSet<HighPoint_DocTypeWorkflowBookmarks>();
            this.HighPoint_Documents = new HashSet<HighPoint_Documents>();
            this.HighPoint_Forms = new HashSet<HighPoint_Forms>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<HighPoint_DocTypeWorkflowBookmarks> HighPoint_DocTypeWorkflowBookmarks { get; set; }
        public virtual ICollection<HighPoint_Documents> HighPoint_Documents { get; set; }
        public virtual ICollection<HighPoint_Forms> HighPoint_Forms { get; set; }
    }
}
