//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_BusinessCalendars
    {
        public HighPoint_BusinessCalendars()
        {
            this.HighPoint_Holidays = new HashSet<HighPoint_Holidays>();
        }
    
        public int Id { get; set; }
        public string FreeWeekDays { get; set; }
    
        public virtual ICollection<HighPoint_Holidays> HighPoint_Holidays { get; set; }
    }
}
