//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_Users
    {
        public HighPoint_Users()
        {
            this.Expenses_Advances = new HashSet<Expenses_Advances>();
            this.Expenses_ExpenseVoucherCases = new HashSet<Expenses_ExpenseVoucherCases>();
            this.Expenses_ExpenseVouchers = new HashSet<Expenses_ExpenseVouchers>();
            this.Expenses_VoucherEmployees = new HashSet<Expenses_VoucherEmployees>();
            this.HighPoint_AutoFormInstances = new HashSet<HighPoint_AutoFormInstances>();
            this.HighPoint_BusinessActivityLogs = new HashSet<HighPoint_BusinessActivityLogs>();
            this.HighPoint_CaseNotes = new HashSet<HighPoint_CaseNotes>();
            this.HighPoint_Documents = new HashSet<HighPoint_Documents>();
            this.HighPoint_Documents1 = new HashSet<HighPoint_Documents>();
            this.HighPoint_Forms = new HashSet<HighPoint_Forms>();
            this.HighPoint_FormTracks = new HashSet<HighPoint_FormTracks>();
            this.HighPoint_ProcessingCases = new HashSet<HighPoint_ProcessingCases>();
            this.HighPoint_ProcessingCases1 = new HashSet<HighPoint_ProcessingCases>();
            this.HighPoint_StateCompletionTracks = new HashSet<HighPoint_StateCompletionTracks>();
            this.HighPoint_StateItemAudits = new HashSet<HighPoint_StateItemAudits>();
            this.HighPoint_StateItems = new HashSet<HighPoint_StateItems>();
            this.HighPoint_Suggestions = new HashSet<HighPoint_Suggestions>();
            this.HighPoint_TaskBases = new HashSet<HighPoint_TaskBases>();
            this.HighPoint_UserGroups1 = new HashSet<HighPoint_UserGroups>();
            this.HighPoint_WorkflowBookmarks = new HashSet<HighPoint_WorkflowBookmarks>();
            this.HighPoint_Roles = new HashSet<HighPoint_Roles>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> RegistrationTime { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string StreetAddress { get; set; }
        public string StreetAddress2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public byte[] Signature { get; set; }
        public Nullable<bool> Deactivated { get; set; }
        public Nullable<bool> HasStandardAvatar { get; set; }
        public Nullable<int> UserGroupFk { get; set; }
        public Nullable<int> CompanyFk { get; set; }
    
        public virtual ICollection<Expenses_Advances> Expenses_Advances { get; set; }
        public virtual Expenses_Companies Expenses_Companies { get; set; }
        public virtual ICollection<Expenses_ExpenseVoucherCases> Expenses_ExpenseVoucherCases { get; set; }
        public virtual ICollection<Expenses_ExpenseVouchers> Expenses_ExpenseVouchers { get; set; }
        public virtual ICollection<Expenses_VoucherEmployees> Expenses_VoucherEmployees { get; set; }
        public virtual ICollection<HighPoint_AutoFormInstances> HighPoint_AutoFormInstances { get; set; }
        public virtual ICollection<HighPoint_BusinessActivityLogs> HighPoint_BusinessActivityLogs { get; set; }
        public virtual ICollection<HighPoint_CaseNotes> HighPoint_CaseNotes { get; set; }
        public virtual ICollection<HighPoint_Documents> HighPoint_Documents { get; set; }
        public virtual ICollection<HighPoint_Documents> HighPoint_Documents1 { get; set; }
        public virtual ICollection<HighPoint_Forms> HighPoint_Forms { get; set; }
        public virtual ICollection<HighPoint_FormTracks> HighPoint_FormTracks { get; set; }
        public virtual ICollection<HighPoint_ProcessingCases> HighPoint_ProcessingCases { get; set; }
        public virtual ICollection<HighPoint_ProcessingCases> HighPoint_ProcessingCases1 { get; set; }
        public virtual ICollection<HighPoint_StateCompletionTracks> HighPoint_StateCompletionTracks { get; set; }
        public virtual ICollection<HighPoint_StateItemAudits> HighPoint_StateItemAudits { get; set; }
        public virtual ICollection<HighPoint_StateItems> HighPoint_StateItems { get; set; }
        public virtual ICollection<HighPoint_Suggestions> HighPoint_Suggestions { get; set; }
        public virtual ICollection<HighPoint_TaskBases> HighPoint_TaskBases { get; set; }
        public virtual HighPoint_UserGroups HighPoint_UserGroups { get; set; }
        public virtual ICollection<HighPoint_UserGroups> HighPoint_UserGroups1 { get; set; }
        public virtual ICollection<HighPoint_WorkflowBookmarks> HighPoint_WorkflowBookmarks { get; set; }
        public virtual ICollection<HighPoint_Roles> HighPoint_Roles { get; set; }
    }
}
