//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HighPointLiteEntities : DbContext
    {
        public HighPointLiteEntities()
            : base("name=HighPointLiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Document> Documents { get; set; }
        public DbSet<DomainEntity> DomainEntities { get; set; }
        public DbSet<Employer> Employers { get; set; }
        public DbSet<Expenses_Advances> Expenses_Advances { get; set; }
        public DbSet<Expenses_Companies> Expenses_Companies { get; set; }
        public DbSet<Expenses_Expenses> Expenses_Expenses { get; set; }
        public DbSet<Expenses_ExpenseVoucherCases> Expenses_ExpenseVoucherCases { get; set; }
        public DbSet<Expenses_ExpenseVouchers> Expenses_ExpenseVouchers { get; set; }
        public DbSet<Expenses_Projects> Expenses_Projects { get; set; }
        public DbSet<Expenses_Reviews> Expenses_Reviews { get; set; }
        public DbSet<Expenses_VoucherEmployees> Expenses_VoucherEmployees { get; set; }
        public DbSet<HighPoint_Addresses> HighPoint_Addresses { get; set; }
        public DbSet<HighPoint_AutoFormInstances> HighPoint_AutoFormInstances { get; set; }
        public DbSet<HighPoint_AutoFormItemInstances> HighPoint_AutoFormItemInstances { get; set; }
        public DbSet<HighPoint_AutoFormItems> HighPoint_AutoFormItems { get; set; }
        public DbSet<HighPoint_AutoForms> HighPoint_AutoForms { get; set; }
        public DbSet<HighPoint_BusinessActivityLogs> HighPoint_BusinessActivityLogs { get; set; }
        public DbSet<HighPoint_BusinessCalendars> HighPoint_BusinessCalendars { get; set; }
        public DbSet<HighPoint_BusinessProcesses> HighPoint_BusinessProcesses { get; set; }
        public DbSet<HighPoint_CaseBusinessActivityLogs> HighPoint_CaseBusinessActivityLogs { get; set; }
        public DbSet<HighPoint_CaseDocuments> HighPoint_CaseDocuments { get; set; }
        public DbSet<HighPoint_CaseNotes> HighPoint_CaseNotes { get; set; }
        public DbSet<HighPoint_DocTypeWorkflowBookmarks> HighPoint_DocTypeWorkflowBookmarks { get; set; }
        public DbSet<HighPoint_Documents> HighPoint_Documents { get; set; }
        public DbSet<HighPoint_DocumentTypes> HighPoint_DocumentTypes { get; set; }
        public DbSet<HighPoint_Features> HighPoint_Features { get; set; }
        public DbSet<HighPoint_Forms> HighPoint_Forms { get; set; }
        public DbSet<HighPoint_FormTracks> HighPoint_FormTracks { get; set; }
        public DbSet<HighPoint_Holidays> HighPoint_Holidays { get; set; }
        public DbSet<HighPoint_NavigatorProcessForms> HighPoint_NavigatorProcessForms { get; set; }
        public DbSet<HighPoint_People> HighPoint_People { get; set; }
        public DbSet<HighPoint_PostMessages> HighPoint_PostMessages { get; set; }
        public DbSet<HighPoint_ProcessAutoForms> HighPoint_ProcessAutoForms { get; set; }
        public DbSet<HighPoint_ProcessFormBookmarks> HighPoint_ProcessFormBookmarks { get; set; }
        public DbSet<HighPoint_ProcessForms> HighPoint_ProcessForms { get; set; }
        public DbSet<HighPoint_ProcessingCases> HighPoint_ProcessingCases { get; set; }
        public DbSet<HighPoint_ProcessingEntities> HighPoint_ProcessingEntities { get; set; }
        public DbSet<HighPoint_Reminders> HighPoint_Reminders { get; set; }
        public DbSet<HighPoint_ReportCategories> HighPoint_ReportCategories { get; set; }
        public DbSet<HighPoint_Reports> HighPoint_Reports { get; set; }
        public DbSet<HighPoint_Roles> HighPoint_Roles { get; set; }
        public DbSet<HighPoint_SelectableOptionBookmarks> HighPoint_SelectableOptionBookmarks { get; set; }
        public DbSet<HighPoint_StateCompletionTracks> HighPoint_StateCompletionTracks { get; set; }
        public DbSet<HighPoint_StateDocuments> HighPoint_StateDocuments { get; set; }
        public DbSet<HighPoint_StateItemAudits> HighPoint_StateItemAudits { get; set; }
        public DbSet<HighPoint_StateItems> HighPoint_StateItems { get; set; }
        public DbSet<HighPoint_Suggestions> HighPoint_Suggestions { get; set; }
        public DbSet<HighPoint_TaskBases> HighPoint_TaskBases { get; set; }
        public DbSet<HighPoint_Tasks> HighPoint_Tasks { get; set; }
        public DbSet<HighPoint_TrackTimeItems> HighPoint_TrackTimeItems { get; set; }
        public DbSet<HighPoint_UserGroups> HighPoint_UserGroups { get; set; }
        public DbSet<HighPoint_Users> HighPoint_Users { get; set; }
        public DbSet<HighPoint_WorkflowBookmarks> HighPoint_WorkflowBookmarks { get; set; }
        public DbSet<HighPoint_WorkflowStatuses> HighPoint_WorkflowStatuses { get; set; }
        public DbSet<HighPoint_WorkflowTracks> HighPoint_WorkflowTracks { get; set; }
        public DbSet<Household> Households { get; set; }
        public DbSet<HouseholdCase> HouseholdCases { get; set; }
        public DbSet<HouseholdPeople> HouseholdPeoples { get; set; }
        public DbSet<IncomeWorksheet> IncomeWorksheets { get; set; }
        public DbSet<LetterDefinition> LetterDefinitions { get; set; }
        public DbSet<Letter> Letters { get; set; }
        public DbSet<MFH_EconomyElements> MFH_EconomyElements { get; set; }
        public DbSet<MFH_HouseholdCases> MFH_HouseholdCases { get; set; }
        public DbSet<MFH_HouseholdPeople> MFH_HouseholdPeople { get; set; }
        public DbSet<MFH_Households> MFH_Households { get; set; }
        public DbSet<MFH_MfhContracts> MFH_MfhContracts { get; set; }
        public DbSet<MFH_PropertyCases> MFH_PropertyCases { get; set; }
        public DbSet<MFH_RecertificationCases> MFH_RecertificationCases { get; set; }
        public DbSet<MFH_Units> MFH_Units { get; set; }
        public DbSet<MyEntity1s> MyEntity1s { get; set; }
        public DbSet<Note> Notes { get; set; }
        public DbSet<ProcessType> ProcessTypes { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Slv_LoanVerificationCases> Slv_LoanVerificationCases { get; set; }
        public DbSet<Slv_Students> Slv_Students { get; set; }
        public DbSet<SystemCas> SystemCases { get; set; }
        public DbSet<SystemUser> SystemUsers { get; set; }
        public DbSet<TaskDefinition> TaskDefinitions { get; set; }
        public DbSet<Task> Tasks { get; set; }
        public DbSet<WorksheetItem> WorksheetItems { get; set; }
    }
}
