//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_WorkflowTracks
    {
        public int StateItemFk { get; set; }
        public string Activity { get; set; }
        public string DetailedTrack { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> CompletionTime { get; set; }
        public string UserId { get; set; }
        public Nullable<int> ProcessingCaseFk { get; set; }
    
        public virtual HighPoint_ProcessingCases HighPoint_ProcessingCases { get; set; }
        public virtual HighPoint_StateItems HighPoint_StateItems { get; set; }
    }
}
