//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_AutoFormItemInstances
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public int AutoFormInstanceFk { get; set; }
        public int AutoFormItemFk { get; set; }
    
        public virtual HighPoint_AutoFormInstances HighPoint_AutoFormInstances { get; set; }
        public virtual HighPoint_AutoFormItems HighPoint_AutoFormItems { get; set; }
    }
}
