//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_People
    {
        public HighPoint_People()
        {
            this.MFH_Units = new HashSet<MFH_Units>();
            this.Slv_Students = new HashSet<Slv_Students>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Ssn { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> ContactFk { get; set; }
    
        public virtual HighPoint_Addresses HighPoint_Addresses { get; set; }
        public virtual ICollection<MFH_Units> MFH_Units { get; set; }
        public virtual MFH_HouseholdPeople MFH_HouseholdPeople { get; set; }
        public virtual ICollection<Slv_Students> Slv_Students { get; set; }
    }
}
