//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_CaseBusinessActivityLogs
    {
        public HighPoint_CaseBusinessActivityLogs()
        {
            this.HighPoint_StateItemAudits = new HashSet<HighPoint_StateItemAudits>();
        }
    
        public int BusinessActivityLogFk { get; set; }
        public Nullable<int> ProcessingCaseFk { get; set; }
    
        public virtual HighPoint_BusinessActivityLogs HighPoint_BusinessActivityLogs { get; set; }
        public virtual HighPoint_ProcessingCases HighPoint_ProcessingCases { get; set; }
        public virtual ICollection<HighPoint_StateItemAudits> HighPoint_StateItemAudits { get; set; }
    }
}
