//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_AutoFormInstances
    {
        public HighPoint_AutoFormInstances()
        {
            this.HighPoint_AutoFormItemInstances = new HashSet<HighPoint_AutoFormItemInstances>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int AutoFormFk { get; set; }
        public int UserCreatedFk { get; set; }
        public Nullable<int> ProcessingCaseFk { get; set; }
    
        public virtual HighPoint_Users HighPoint_Users { get; set; }
        public virtual HighPoint_ProcessingCases HighPoint_ProcessingCases { get; set; }
        public virtual HighPoint_AutoForms HighPoint_AutoForms { get; set; }
        public virtual ICollection<HighPoint_AutoFormItemInstances> HighPoint_AutoFormItemInstances { get; set; }
    }
}
