//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_Roles
    {
        public HighPoint_Roles()
        {
            this.HighPoint_Reports = new HashSet<HighPoint_Reports>();
            this.HighPoint_Features = new HashSet<HighPoint_Features>();
            this.HighPoint_Users = new HashSet<HighPoint_Users>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string HardcodedName { get; set; }
    
        public virtual ICollection<HighPoint_Reports> HighPoint_Reports { get; set; }
        public virtual ICollection<HighPoint_Features> HighPoint_Features { get; set; }
        public virtual ICollection<HighPoint_Users> HighPoint_Users { get; set; }
    }
}
