//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HighPoint_FormTracks
    {
        public int StateItemFk { get; set; }
        public Nullable<System.DateTime> RequesteTime { get; set; }
        public Nullable<int> UserRequestedFk { get; set; }
        public Nullable<int> FormFk { get; set; }
        public Nullable<int> DocumentFk { get; set; }
    
        public virtual HighPoint_Documents HighPoint_Documents { get; set; }
        public virtual HighPoint_Forms HighPoint_Forms { get; set; }
        public virtual HighPoint_Users HighPoint_Users { get; set; }
        public virtual HighPoint_StateItems HighPoint_StateItems { get; set; }
    }
}
