//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Household
    {
        public Household()
        {
            this.HouseholdCases = new HashSet<HouseholdCase>();
            this.HouseholdPeoples = new HashSet<HouseholdPeople>();
        }
    
        public int DomainEntityId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string TenantId { get; set; }
        public Nullable<System.DateTime> MoveInDate { get; set; }
        public Nullable<System.DateTime> NextRecertificationDate { get; set; }
        public Nullable<int> HousingSpecialistId { get; set; }
        public Nullable<int> HohId { get; set; }
    
        public virtual DomainEntity DomainEntity { get; set; }
        public virtual ICollection<HouseholdCase> HouseholdCases { get; set; }
        public virtual HouseholdPeople HouseholdPeople { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<HouseholdPeople> HouseholdPeoples { get; set; }
    }
}
