//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseholdCase
    {
        public HouseholdCase()
        {
            this.IncomeWorksheets = new HashSet<IncomeWorksheet>();
        }
    
        public int SystemCaseId { get; set; }
        public Nullable<System.DateTime> DueMonth { get; set; }
        public Nullable<System.DateTime> RecertificationDate { get; set; }
        public Nullable<int> HouseholdId { get; set; }
    
        public virtual Household Household { get; set; }
        public virtual ICollection<IncomeWorksheet> IncomeWorksheets { get; set; }
        public virtual SystemCas SystemCas { get; set; }
    }
}
