//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFH_HouseholdCases
    {
        public MFH_HouseholdCases()
        {
            this.MFH_EconomyElements = new HashSet<MFH_EconomyElements>();
        }
    
        public int ProcessingCaseFk { get; set; }
        public string Description { get; set; }
        public Nullable<int> HouseholdFk { get; set; }
    
        public virtual HighPoint_ProcessingCases HighPoint_ProcessingCases { get; set; }
        public virtual ICollection<MFH_EconomyElements> MFH_EconomyElements { get; set; }
        public virtual MFH_Households MFH_Households { get; set; }
        public virtual MFH_RecertificationCases MFH_RecertificationCases { get; set; }
    }
}
