//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class MFH_EconomyElements
    {
        public int Id { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> HouseholdCaseFk { get; set; }
        public Nullable<int> HouseholdPersonFk { get; set; }
    
        public virtual MFH_HouseholdPeople MFH_HouseholdPeople { get; set; }
        public virtual MFH_HouseholdCases MFH_HouseholdCases { get; set; }
    }
}
