//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemCas
    {
        public SystemCas()
        {
            this.Documents = new HashSet<Document>();
            this.Tasks = new HashSet<Task>();
        }
    
        public int SystemCaseId { get; set; }
        public string Description { get; set; }
        public string CaseStatus { get; set; }
        public Nullable<int> ProcessTypeId { get; set; }
        public Nullable<int> DomainEntityId { get; set; }
    
        public virtual ICollection<Document> Documents { get; set; }
        public virtual DomainEntity DomainEntity { get; set; }
        public virtual HouseholdCase HouseholdCase { get; set; }
        public virtual ProcessType ProcessType { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
