//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskDefinition
    {
        public TaskDefinition()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int TaskDefinitionId { get; set; }
        public string Name { get; set; }
        public string EditUrl { get; set; }
        public string PartialUrl { get; set; }
        public Nullable<int> ProcessTypeId { get; set; }
    
        public virtual ProcessType ProcessType { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
