//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mcchkn
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.Letters = new HashSet<Letter>();
            this.Notes = new HashSet<Note>();
        }
    
        public int TaskId { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<int> SystemCaseId { get; set; }
        public Nullable<int> SystemUserId { get; set; }
        public Nullable<int> TaskDefinitionId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Letter> Letters { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual SystemCas SystemCas { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual TaskDefinition TaskDefinition { get; set; }
    }
}
